version: "3"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://127.0.0.1:6379/0
      - FLOWER_PORT=8888
    ports:
      - 8888:8888