version: "3"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: "tree_db"
      POSTGRES_USER: "alexander"
      POSTGRES_PASSWORD: "123"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"